/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/about-api';
export * from './apis/application-field-api';
export * from './apis/application-question-api';
export * from './apis/application-session-api';
export * from './apis/coming-soon-api';
export * from './apis/contributor-api';
export * from './apis/featured-api';
export * from './apis/homepage-api';
export * from './apis/imprint-api';
export * from './apis/serie-api';
export * from './apis/upload-file-api';
export * from './apis/users-permissions-permission-api';
export * from './apis/users-permissions-role-api';
export * from './apis/users-permissions-user-api';
export * from './apis/video-api';

