/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutListResponseAttributes } from './about-list-response-attributes';
/**
 * 
 * @export
 * @interface AboutListResponseData
 */
export interface AboutListResponseData {
    /**
     * 
     * @type {string}
     * @memberof AboutListResponseData
     */
    id?: string;
    /**
     * 
     * @type {AboutListResponseAttributes}
     * @memberof AboutListResponseData
     */
    attributes?: AboutListResponseAttributes;
}
