/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissions } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers } from './about-localization-response-created-by-data-attributes-roles-attributes-users';
/**
 * 
 * @export
 * @interface AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
 */
export interface AboutLocalizationResponseCreatedByDataAttributesRolesAttributes {
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    description?: string;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    users?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissions}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    permissions?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissions;
    /**
     * 
     * @type {Date}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof AboutLocalizationResponseCreatedByDataAttributesRolesAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
