/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutListResponseData } from './about-list-response-data';
import { AboutListResponseMeta } from './about-list-response-meta';
/**
 * 
 * @export
 * @interface AboutListResponse
 */
export interface AboutListResponse {
    /**
     * 
     * @type {Array<AboutListResponseData>}
     * @memberof AboutListResponse
     */
    data?: Array<AboutListResponseData>;
    /**
     * 
     * @type {AboutListResponseMeta}
     * @memberof AboutListResponse
     */
    meta?: AboutListResponseMeta;
}
