/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRoles } from './about-localization-response-created-by-data-attributes-roles';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
/**
 * 
 * @export
 * @interface AboutLocalizationResponseCreatedByDataAttributes
 */
export interface AboutLocalizationResponseCreatedByDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    firstname?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    lastname?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    resetPasswordToken?: string;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    registrationToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    isActive?: boolean;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRoles}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    roles?: AboutLocalizationResponseCreatedByDataAttributesRoles;
    /**
     * 
     * @type {boolean}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    blocked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    preferedLanguage?: string;
    /**
     * 
     * @type {Date}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof AboutLocalizationResponseCreatedByDataAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
