/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes } from './application-field-list-response-attributes-applications-attributes-field-data-attributes';
/**
 * 
 * @export
 * @interface ApplicationFieldListResponseAttributesApplicationsAttributesFieldData
 */
export interface ApplicationFieldListResponseAttributesApplicationsAttributesFieldData {
    /**
     * 
     * @type {string}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldData
     */
    id?: string;
    /**
     * 
     * @type {ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldData
     */
    attributes?: ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes;
}
