/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestionsAttributes } from './application-field-list-response-attributes-applications-attributes-field-data-attributes-questions-attributes';
/**
 * 
 * @export
 * @interface ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestionsData
 */
export interface ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestionsData {
    /**
     * 
     * @type {string}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestionsData
     */
    id?: string;
    /**
     * 
     * @type {ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestionsAttributes}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestionsData
     */
    attributes?: ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestionsAttributes;
}
