/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ApplicationFieldRequestData
 */
export interface ApplicationFieldRequestData {
    /**
     * 
     * @type {string}
     * @memberof ApplicationFieldRequestData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationFieldRequestData
     */
    description: string;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof ApplicationFieldRequestData
     */
    applications?: Array<number | string>;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof ApplicationFieldRequestData
     */
    questions?: Array<number | string>;
}
