/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers } from './about-localization-response-created-by-data-attributes-roles-attributes-users';
import { ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestions } from './application-field-list-response-attributes-applications-attributes-field-data-attributes-questions';
/**
 * 
 * @export
 * @interface ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
 */
export interface ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    description?: string;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    applications?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers;
    /**
     * 
     * @type {ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestions}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    questions?: ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributesQuestions;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ApplicationFieldListResponseAttributesApplicationsAttributesFieldDataAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
