/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { ApplicationQuestionListResponseAttributesFieldDataAttributesApplications } from './application-question-list-response-attributes-field-data-attributes-applications';
import { ApplicationQuestionListResponseAttributesFieldDataAttributesQuestions } from './application-question-list-response-attributes-field-data-attributes-questions';
/**
 * 
 * @export
 * @interface ApplicationQuestionListResponseAttributesFieldDataAttributes
 */
export interface ApplicationQuestionListResponseAttributesFieldDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    description?: string;
    /**
     * 
     * @type {ApplicationQuestionListResponseAttributesFieldDataAttributesApplications}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    applications?: ApplicationQuestionListResponseAttributesFieldDataAttributesApplications;
    /**
     * 
     * @type {ApplicationQuestionListResponseAttributesFieldDataAttributesQuestions}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    questions?: ApplicationQuestionListResponseAttributesFieldDataAttributesQuestions;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ApplicationQuestionListResponseAttributesFieldDataAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
