/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutListResponseMeta } from './about-list-response-meta';
import { ContributorListResponseData } from './contributor-list-response-data';
/**
 * 
 * @export
 * @interface ContributorListResponse
 */
export interface ContributorListResponse {
    /**
     * 
     * @type {Array<ContributorListResponseData>}
     * @memberof ContributorListResponse
     */
    data?: Array<ContributorListResponseData>;
    /**
     * 
     * @type {AboutListResponseMeta}
     * @memberof ContributorListResponse
     */
    meta?: AboutListResponseMeta;
}
