/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedBy } from './about-localization-response-created-by';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { ContributorListResponseAttributesImage } from './contributor-list-response-attributes-image';
/**
 * 
 * @export
 * @interface ContributorListResponseAttributes
 */
export interface ContributorListResponseAttributes {
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributes
     */
    name?: string;
    /**
     * 
     * @type {ContributorListResponseAttributesImage}
     * @memberof ContributorListResponseAttributes
     */
    image?: ContributorListResponseAttributesImage;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributes
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributes
     */
    href?: string;
    /**
     * 
     * @type {Date}
     * @memberof ContributorListResponseAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ContributorListResponseAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedBy}
     * @memberof ContributorListResponseAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedBy;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ContributorListResponseAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
