/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers } from './about-localization-response-created-by-data-attributes-roles-attributes-users';
import { ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFiles } from './contributor-list-response-attributes-image-data-attributes-folder-data-attributes-files';
/**
 * 
 * @export
 * @interface ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
 */
export interface ContributorListResponseAttributesImageDataAttributesFolderDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    pathId?: number;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    parent?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    children?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers;
    /**
     * 
     * @type {ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFiles}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    files?: ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFiles;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    path?: string;
    /**
     * 
     * @type {Date}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
