/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedBy } from './about-localization-response-created-by';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers } from './about-localization-response-created-by-data-attributes-roles-attributes-users';
/**
 * 
 * @export
 * @interface ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
 */
export interface ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes {
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    alternativeText?: string;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    caption?: string;
    /**
     * 
     * @type {number}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    height?: number;
    /**
     * 
     * @type {any}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    formats?: any;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    ext?: string;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    previewUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    provider?: string;
    /**
     * 
     * @type {any}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    providerMetadata?: any;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    related?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    folder?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {string}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    folderPath?: string;
    /**
     * 
     * @type {Date}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedBy}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedBy;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof ContributorListResponseAttributesImageDataAttributesFolderDataAttributesFilesAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
