/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeaturedListResponseData } from './featured-list-response-data';
/**
 * 
 * @export
 * @interface FeaturedResponse
 */
export interface FeaturedResponse {
    /**
     * 
     * @type {FeaturedListResponseData}
     * @memberof FeaturedResponse
     */
    data?: FeaturedListResponseData;
    /**
     * 
     * @type {any}
     * @memberof FeaturedResponse
     */
    meta?: any;
}
