/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeaturedRequestData } from './featured-request-data';
/**
 * 
 * @export
 * @interface FeaturedRequest
 */
export interface FeaturedRequest {
    /**
     * 
     * @type {FeaturedRequestData}
     * @memberof FeaturedRequest
     */
    data: FeaturedRequestData;
}
