/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutListResponseMeta } from './about-list-response-meta';
import { FeaturedListResponseData } from './featured-list-response-data';
/**
 * 
 * @export
 * @interface FeaturedListResponse
 */
export interface FeaturedListResponse {
    /**
     * 
     * @type {Array<FeaturedListResponseData>}
     * @memberof FeaturedListResponse
     */
    data?: Array<FeaturedListResponseData>;
    /**
     * 
     * @type {AboutListResponseMeta}
     * @memberof FeaturedListResponse
     */
    meta?: AboutListResponseMeta;
}
