/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
/**
 * 
 * @export
 * @interface FeaturedListResponseAttributesVideoDataAttributesContributors
 */
export interface FeaturedListResponseAttributesVideoDataAttributesContributors {
    /**
     * 
     * @type {string}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesContributors
     */
    id?: string;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesContributors
     */
    contributor?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {string}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesContributors
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesContributors
     */
    character?: string;
}
