/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeaturedListResponseAttributesVideoDataAttributesOnWatchlistAttributesRoleDataAttributesPermissionsData } from './featured-list-response-attributes-video-data-attributes-on-watchlist-attributes-role-data-attributes-permissions-data';
/**
 * 
 * @export
 * @interface FeaturedListResponseAttributesVideoDataAttributesOnWatchlistAttributesRoleDataAttributesPermissions
 */
export interface FeaturedListResponseAttributesVideoDataAttributesOnWatchlistAttributesRoleDataAttributesPermissions {
    /**
     * 
     * @type {Array<FeaturedListResponseAttributesVideoDataAttributesOnWatchlistAttributesRoleDataAttributesPermissionsData>}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesOnWatchlistAttributesRoleDataAttributesPermissions
     */
    data?: Array<FeaturedListResponseAttributesVideoDataAttributesOnWatchlistAttributesRoleDataAttributesPermissionsData>;
}
