/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributor } from './featured-list-response-attributes-video-data-attributes-series-data-attributes-contributor';
/**
 * 
 * @export
 * @interface FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributors
 */
export interface FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributors {
    /**
     * 
     * @type {string}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributors
     */
    id?: string;
    /**
     * 
     * @type {FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributor}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributors
     */
    contributor?: FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributor;
    /**
     * 
     * @type {string}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributors
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof FeaturedListResponseAttributesVideoDataAttributesSeriesDataAttributesContributors
     */
    character?: string;
}
