/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedBy } from './about-localization-response-created-by';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
/**
 * 
 * @export
 * @interface HomepageLocalizationResponse
 */
export interface HomepageLocalizationResponse {
    /**
     * 
     * @type {string}
     * @memberof HomepageLocalizationResponse
     */
    id?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof HomepageLocalizationResponse
     */
    page?: Array<any>;
    /**
     * 
     * @type {Date}
     * @memberof HomepageLocalizationResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof HomepageLocalizationResponse
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof HomepageLocalizationResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedBy}
     * @memberof HomepageLocalizationResponse
     */
    createdBy?: AboutLocalizationResponseCreatedBy;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof HomepageLocalizationResponse
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {Array<any>}
     * @memberof HomepageLocalizationResponse
     */
    localizations?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof HomepageLocalizationResponse
     */
    locale?: string;
}
