/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UploadFolderListResponseAttributes } from './upload-folder-list-response-attributes';
/**
 * 
 * @export
 * @interface UploadFolderListResponseData
 */
export interface UploadFolderListResponseData {
    /**
     * 
     * @type {string}
     * @memberof UploadFolderListResponseData
     */
    id?: string;
    /**
     * 
     * @type {UploadFolderListResponseAttributes}
     * @memberof UploadFolderListResponseData
     */
    attributes?: UploadFolderListResponseAttributes;
}
