/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutListResponseMeta } from './about-list-response-meta';
import { ContributorListResponseAttributesImageData } from './contributor-list-response-attributes-image-data';
/**
 * 
 * @export
 * @interface UploadFileListResponse
 */
export interface UploadFileListResponse {
    /**
     * 
     * @type {Array<ContributorListResponseAttributesImageData>}
     * @memberof UploadFileListResponse
     */
    data?: Array<ContributorListResponseAttributesImageData>;
    /**
     * 
     * @type {AboutListResponseMeta}
     * @memberof UploadFileListResponse
     */
    meta?: AboutListResponseMeta;
}
