/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersPermissionsRoleListResponseData } from './users-permissions-role-list-response-data';
/**
 * 
 * @export
 * @interface UsersPermissionsRoleResponse
 */
export interface UsersPermissionsRoleResponse {
    /**
     * 
     * @type {UsersPermissionsRoleListResponseData}
     * @memberof UsersPermissionsRoleResponse
     */
    data?: UsersPermissionsRoleListResponseData;
    /**
     * 
     * @type {any}
     * @memberof UsersPermissionsRoleResponse
     */
    meta?: any;
}
