/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UsersPermissionsUserRequestData
 */
export interface UsersPermissionsUserRequestData {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    resetPasswordToken?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUserRequestData
     */
    confirmationToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUserRequestData
     */
    confirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUserRequestData
     */
    blocked?: boolean;
    /**
     * 
     * @type {number | string}
     * @memberof UsersPermissionsUserRequestData
     */
    role?: number | string;
    /**
     * 
     * @type {Array<number | string>}
     * @memberof UsersPermissionsUserRequestData
     */
    watchlist?: Array<number | string>;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUserRequestData
     */
    admin?: boolean;
    /**
     * 
     * @type {number | string}
     * @memberof UsersPermissionsUserRequestData
     */
    image?: number | string;
}
