/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsersPermissionsRoleListResponseAttributesPermissionsAttributesRoleDataAttributesUsersAttributesWatchlistAttributes } from './users-permissions-role-list-response-attributes-permissions-attributes-role-data-attributes-users-attributes-watchlist-attributes';
/**
 * 
 * @export
 * @interface UsersPermissionsRoleListResponseAttributesPermissionsAttributesRoleDataAttributesUsersAttributesWatchlistData
 */
export interface UsersPermissionsRoleListResponseAttributesPermissionsAttributesRoleDataAttributesUsersAttributesWatchlistData {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRoleListResponseAttributesPermissionsAttributesRoleDataAttributesUsersAttributesWatchlistData
     */
    id?: string;
    /**
     * 
     * @type {UsersPermissionsRoleListResponseAttributesPermissionsAttributesRoleDataAttributesUsersAttributesWatchlistAttributes}
     * @memberof UsersPermissionsRoleListResponseAttributesPermissionsAttributesRoleDataAttributesUsersAttributesWatchlistData
     */
    attributes?: UsersPermissionsRoleListResponseAttributesPermissionsAttributesRoleDataAttributesUsersAttributesWatchlistAttributes;
}
