/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { UsersPermissionsPermissionListResponseAttributesRole } from './users-permissions-permission-list-response-attributes-role';
/**
 * 
 * @export
 * @interface UsersPermissionsPermissionListResponseAttributes
 */
export interface UsersPermissionsPermissionListResponseAttributes {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsPermissionListResponseAttributes
     */
    action?: string;
    /**
     * 
     * @type {UsersPermissionsPermissionListResponseAttributesRole}
     * @memberof UsersPermissionsPermissionListResponseAttributes
     */
    role?: UsersPermissionsPermissionListResponseAttributesRole;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsPermissionListResponseAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsPermissionListResponseAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof UsersPermissionsPermissionListResponseAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof UsersPermissionsPermissionListResponseAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
