/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistData } from './video-localization-response-series-data-attributes-videos-attributes-on-watchlist-data';
/**
 * 
 * @export
 * @interface VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlist
 */
export interface VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlist {
    /**
     * 
     * @type {Array<VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistData>}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlist
     */
    data?: Array<VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistData>;
}
