/* tslint:disable */
/* eslint-disable */
/**
 * Bergflix. Api Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@bergflix.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole } from './about-localization-response-created-by-data-attributes-roles-attributes-permissions-attributes-role';
import { AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers } from './about-localization-response-created-by-data-attributes-roles-attributes-users';
import { VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributesPermissions } from './video-localization-response-series-data-attributes-videos-attributes-on-watchlist-attributes-role-data-attributes-permissions';
/**
 * 
 * @export
 * @interface VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
 */
export interface VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    type?: string;
    /**
     * 
     * @type {VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributesPermissions}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    permissions?: VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributesPermissions;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    users?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesUsers;
    /**
     * 
     * @type {Date}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    createdBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
    /**
     * 
     * @type {AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole}
     * @memberof VideoLocalizationResponseSeriesDataAttributesVideosAttributesOnWatchlistAttributesRoleDataAttributes
     */
    updatedBy?: AboutLocalizationResponseCreatedByDataAttributesRolesAttributesPermissionsAttributesRole;
}
